# Generated by Django 6.0.4 on 2026-04-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('gambar', models.ImageField(upload_to='banner/')),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
    ]
