# Generated by Django 6.0.4 on 2026-04-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentangKami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('keunggulan', models.TextField(help_text='Pisahkan dengan enter per poin')),
                ('whatsapp', models.CharField(max_length=20)),
            ],
        ),
    ]
