# Generated by Django 6.0.4 on 2026-04-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_tentangkami'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(max_length=100)),
                ('nomor_wa', models.CharField(max_length=20)),
            ],
        ),
    ]
