# Generated by Django 6.0.4 on 2026-04-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_settingwebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingwebsite',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
