# Generated by Django 6.0.4 on 2026-04-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_settingwebsite_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingwebsite',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon/'),
        ),
    ]
