# Generated by Django 6.0.4 on 2026-04-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_settingwebsite_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('konten', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='artikel/')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
