# Generated by Django 6.0.4 on 2026-05-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_artikel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namacus', models.CharField(max_length=100)),
                ('komentar', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='testimoni/')),
            ],
        ),
    ]
